language: groovy

jdk:
  - oraclejdk7
  - openjdk7
# runs slowly and often fails due to insufficient wait times in tests, found JDK8 to be faster than JDK7 in other environments, commenting for now:
#  - oraclejdk8

script:
  - gradle cleanAll load
  - gradle check
  - gradle test --info
